{
 "title": "Kong(eni)",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (http://github.com/kong/kong-plugin-prometheus)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(kong_http_status,service)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(kong_http_eni_status,route)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(kong_http_eni_status,method)"
    }
   },
   {
    "name": "code",
    "query": {
     "query": "label_values(kong_http_eni_status,code)"
    }
   },
   {
    "name": "consumer",
    "query": {
     "query": "label_values(kong_http_eni_status,consumer)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kong_http_eni_status,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request rate eni",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS per route($route) by consumer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_eni_status{instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\",code=~\"$code\"}[1m])) by (route,consumer)",
       "legendFormat": "{{route}}---{{consumer}}"
      }
     ]
    },
    {
     "title": "RPS per route($route) by method",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_eni_status{instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\",code=~\"$code\"}[1m])) by (route,method)",
       "legendFormat": "{{route}}---{{method}}"
      }
     ]
    },
    {
     "title": "RPS per route($route) by code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_eni_status{instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\",code=~\"$code\"}[1m])) by (route,code)",
       "legendFormat": "{{route}}---{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latencies eni",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kong proxy latency per route",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_eni_latency_bucket{type=\"kong\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_eni_latency_bucket{type=\"kong\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_eni_latency_bucket{type=\"kong\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    },
    {
     "title": "Kong proxy latency per route/consumer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_eni_latency_bucket{type=\"kong\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, consumer, le))",
       "legendFormat": "p90-{{route}}---{{consumer}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_eni_latency_bucket{type=\"kong\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, consumer, le))",
       "legendFormat": "p95-{{route}}---{{consumer}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_eni_latency_bucket{type=\"kong\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, consumer, le))",
       "legendFormat": "p99-{{route}}---{{consumer}}"
      }
     ]
    },
    {
     "title": "Request time per route",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_eni_latency_bucket{type=\"request\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_eni_latency_bucket{type=\"request\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_eni_latency_bucket{type=\"request\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    },
    {
     "title": "Request time per route/consumer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_eni_latency_bucket{type=\"request\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, consumer, le))",
       "legendFormat": "p90-{{route}}---{{consumer}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_eni_latency_bucket{type=\"request\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, consumer, le))",
       "legendFormat": "p95-{{route}}---{{consumer}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_eni_latency_bucket{type=\"request\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, consumer, le))",
       "legendFormat": "p99-{{route}}---{{consumer}}"
      }
     ]
    },
    {
     "title": "Upstream time per route",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_eni_latency_bucket{type=\"upstream\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_eni_latency_bucket{type=\"upstream\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_eni_latency_bucket{type=\"upstream\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    },
    {
     "title": "Upstream time per route/consumer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_eni_latency_bucket{type=\"upstream\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, consumer, le))",
       "legendFormat": "p90-{{route}}---{{consumer}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_eni_latency_bucket{type=\"upstream\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, consumer, le))",
       "legendFormat": "p95-{{route}}---{{consumer}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_eni_latency_bucket{type=\"upstream\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m]))by(route, consumer, le))",
       "legendFormat": "p99-{{route}}---{{consumer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth eni",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Egress per route",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_eni_bandwidth{type=\"egress\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m])) by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Egress per consumer ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_eni_bandwidth{type=\"egress\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m])) by (consumer)",
       "legendFormat": "{{consumer}}"
      }
     ]
    },
    {
     "title": "Ingress per route",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_eni_bandwidth{type=\"ingress\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m])) by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Ingress per consumer ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_eni_bandwidth{type=\"ingress\", instance=~\"$instance\", service=~\"$service\", route=~\"$route\",consumer=~\"$consumer\",method=~\"$method\"}[1m])) by (consumer)",
       "legendFormat": "{{consumer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total requests per second (RPS)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_status{instance=~\"$instance\"}[1m]))",
       "legendFormat": "Requests/second"
      }
     ]
    },
    {
     "title": "RPS per service ($service)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_status{service=~\"$service\", instance=~\"$instance\"}[1m])) by (service)",
       "legendFormat": "service:{{service}}"
      }
     ]
    },
    {
     "title": "RPS per service by status code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_status{service=~\"$service\", instance=~\"$instance\"}[1m])) by (service,code)",
       "legendFormat": "service:{{service}}-{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kong Proxy Latency across all services",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"kong\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"kong\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"kong\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"kong\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"kong\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"kong\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Route",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"kong\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"kong\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"kong\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    },
    {
     "title": "Request Time across all services",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"request\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"request\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"request\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Request Time per service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"request\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"request\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"request\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      }
     ]
    },
    {
     "title": "Request Time per Route",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"request\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"request\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"request\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    },
    {
     "title": "Upstream time across all services",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"upstream\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"upstream\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"upstream\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Upstream Time across per service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"upstream\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"upstream\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"upstream\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      }
     ]
    },
    {
     "title": "Upstream Time across per Route",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"upstream\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"upstream\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"upstream\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_bandwidth{instance=~\"$instance\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Egress per service/route",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_bandwidth{type=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service)",
       "legendFormat": "service:{{service}}"
      },
      {
       "expr": "sum(irate(kong_bandwidth{type=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route)",
       "legendFormat": "route:{{route}}"
      }
     ]
    },
    {
     "title": "Ingress per service/route",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_bandwidth{type=\"ingress\", service =~\"$service\"}[1m])) by (service)",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kong memory usage by Node ($instance)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kong_memory_lua_shared_dict_bytes{instance=~\"$instance\"}/kong_memory_lua_shared_dict_total_bytes{instance=~\"$instance\"})*100",
       "legendFormat": "{{shared_dict}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx connection state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_nginx_http_current_connections{state=~\"active|reading|writing|waiting\", instance=~\"$instance\"}[1m])) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Total Connections",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kong_nginx_http_current_connections{state=\"total\", instance=~\"$instance\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Handled Connections",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kong_nginx_http_current_connections{state=\"handled\", instance=~\"$instance\"})",
       "legendFormat": "Handled"
      }
     ]
    },
    {
     "title": "Accepted Connections",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kong_nginx_http_current_connections{state=\"accepted\", instance=~\"$instance\"})",
       "legendFormat": "Accepted"
      }
     ]
    }
   ]
  }
 ]
}