{
 "title": "Kong (official) 3.1.1 (ENI Version)",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (http://github.com/kong/kong)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clusterID",
    "label": "clusterID",
    "query": {
     "query": "label_values({__name__=~\"^kong.*\"},clusterID)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values({__name__=~\"^kong.*\",clusterID=~\"$clusterID\"},namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values({__name__=~\"^kong.*\",pod=~\"stargate-.*\",clusterID=~\"$clusterID\"},pod)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({__name__=~\"^kong.*\",pod=~\"$deployment-[0-9a-f]*-.*\",clusterID=~\"$clusterID\"},pod)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values({__name__=~\"kong_http_requests_total|kong_kong_latency_ms_bucket\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"},route)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values({__name__=~\"kong_http_requests_total|kong_kong_latency_ms_bucket\"},exported_service)"
    }
   },
   {
    "name": "upstream",
    "query": {
     "query": "label_values(kong_upstream_target_health{pod=~\"$pod\"}, upstream)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kong shared memory usage by Node ($pod)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(kong_memory_lua_shared_dict_bytes{clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\",shared_dict!~\"kong_process_events\"}/kong_memory_lua_shared_dict_total_bytes{clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\",shared_dict!~\"kong_process_events\"})*100",
     "legendFormat": "{{shared_dict}} ({{kong_subsystem}})"
    }
   ]
  },
  {
   "title": "Kong worker Lua VM usage by Node ($pod)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "repeat": "pod",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kong_memory_workers_lua_vms_bytes{clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "PID:{{pid}} ({{kong_subsystem}})"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx connection state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{state=~\"active|reading|writing|waiting\", clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Total Connections",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{state=\"total\", clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Handled Connections",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{state=\"handled\", clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "Handled"
      }
     ]
    },
    {
     "title": "Accepted Connections",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{state=\"accepted\", clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "Accepted"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rate (Need to set config.status_code_metrics, it will cause performance impact)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Total requests per second (RPS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kong_http_requests_total{clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Requests/second"
    }
   ]
  },
  {
   "title": "RPS per route/service ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "RPS per route/service by status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service,code)",
     "legendFormat": "service:{{service}}-{{code}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route,code)",
     "legendFormat": "route:{{route}}-{{code}}"
    }
   ]
  },
  {
   "title": "Latencies (Need to set config.latency_metrics, it will cause performance impact)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kong Proxy Latency across all services",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Route",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    },
    {
     "title": "Request Time across all services",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Request Time per service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      }
     ]
    },
    {
     "title": "Request Time per Route",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    },
    {
     "title": "Upstream time across all services",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Upstream Time across per service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      }
     ]
    },
    {
     "title": "Upstream Time across per Route",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth (Need to set config.bandwidth_metrics, it will cause performance impact)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_bandwidth_bytes{clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Egress per service/route",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_bandwidth_bytes{direction=\"egress\", service =~\"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (service)",
       "legendFormat": "service:{{service}}"
      },
      {
       "expr": "sum(irate(kong_bandwidth_bytes{direction=\"egress\", service =~\"$service\",route=~\"$route\",clusterID=~\"$clusterID\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (route)",
       "legendFormat": "route:{{route}}"
      }
     ]
    },
    {
     "title": "Ingress per service/route",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_bandwidth_bytes{direction=\"ingress\", service =~\"$service\"}[1m])) by (service)",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream  (Need to set config.upstream_health_metrics, it will cause performance impact)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Healthy status",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(kong_upstream_target_health{state=\"healthy\",upstream=~\"$upstream\"}) by (upstream,target,address) * -1  + sum(kong_upstream_target_health{state=~\"(unhealthy|dns_error)\",upstream=~\"$upstream\"}) by (upstream,target,address)",
       "legendFormat": "{{upstream}}:{{target}}::{{address}}"
      }
     ]
    },
    {
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(\n# map state to a numeric value\n# since grafana doesn't support value mapping yet\n  label_replace(\n    label_replace(\n      label_replace(\n       kong_upstream_target_health{upstream=~\"$upstream\"}\n       # healthy is positive number\n       , \"state_value\", \"1\", \"state\", \"healthy\"\n       # healthchecks_off is 0\n      ), \"state_value\", \"0\", \"state\", \"healthchecks_off\"\n      # unhealthy is negative number\n    ), \"state_value\", \"-1\", \"state\", \"(dns_error|unhealthy)\"\n  )\n)\nby (upstream, target, address, state, state_value) > 0"
      }
     ]
    }
   ]
  }
 ]
}